# Generated by Django 5.1.9 on 2025-05-24 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('chef', 'Chef'), ('waiter', 'Waiter'), ('team_member', 'Team Member'), ('customer', 'Customer')], default='Customer', max_length=20),
        ),
    ]
