# Generated by Django 5.1.9 on 2025-05-24 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_extra_remove_menu_price_portion'),
        ('order', '0003_orderitem_extras_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='menu_item',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='portion',
            field=models.ForeignKey(default='872b8d96-83c4-4a32-9d35-08463cef65c7', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='items.portion'),
            preserve_default=False,
        ),
    ]
